# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francis/Downloads/Hotel-Management-System-in-C--main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francis/Downloads/Hotel-Management-System-in-C--main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francis/Downloads/Hotel-Management-System-in-C--main/CMakeFiles /home/francis/Downloads/Hotel-Management-System-in-C--main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francis/Downloads/Hotel-Management-System-in-C--main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Hotel_Management_System_in_C_

# Build rule for target.
Hotel_Management_System_in_C_: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hotel_Management_System_in_C_
.PHONY : Hotel_Management_System_in_C_

# fast build rule for target.
Hotel_Management_System_in_C_/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/build
.PHONY : Hotel_Management_System_in_C_/fast

app.o: app.cpp.o

.PHONY : app.o

# target to build an object file
app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/app.cpp.o
.PHONY : app.cpp.o

app.i: app.cpp.i

.PHONY : app.i

# target to preprocess a source file
app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/app.cpp.i
.PHONY : app.cpp.i

app.s: app.cpp.s

.PHONY : app.s

# target to generate assembly for a file
app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/app.cpp.s
.PHONY : app.cpp.s

customer.o: customer.cpp.o

.PHONY : customer.o

# target to build an object file
customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/customer.cpp.o
.PHONY : customer.cpp.o

customer.i: customer.cpp.i

.PHONY : customer.i

# target to preprocess a source file
customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/customer.cpp.i
.PHONY : customer.cpp.i

customer.s: customer.cpp.s

.PHONY : customer.s

# target to generate assembly for a file
customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/customer.cpp.s
.PHONY : customer.cpp.s

hotel.o: hotel.cpp.o

.PHONY : hotel.o

# target to build an object file
hotel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/hotel.cpp.o
.PHONY : hotel.cpp.o

hotel.i: hotel.cpp.i

.PHONY : hotel.i

# target to preprocess a source file
hotel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/hotel.cpp.i
.PHONY : hotel.cpp.i

hotel.s: hotel.cpp.s

.PHONY : hotel.s

# target to generate assembly for a file
hotel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/hotel.cpp.s
.PHONY : hotel.cpp.s

room.o: room.cpp.o

.PHONY : room.o

# target to build an object file
room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/room.cpp.o
.PHONY : room.cpp.o

room.i: room.cpp.i

.PHONY : room.i

# target to preprocess a source file
room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/room.cpp.i
.PHONY : room.cpp.i

room.s: room.cpp.s

.PHONY : room.s

# target to generate assembly for a file
room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/room.cpp.s
.PHONY : room.cpp.s

user.o: user.cpp.o

.PHONY : user.o

# target to build an object file
user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/user.cpp.o
.PHONY : user.cpp.o

user.i: user.cpp.i

.PHONY : user.i

# target to preprocess a source file
user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/user.cpp.i
.PHONY : user.cpp.i

user.s: user.cpp.s

.PHONY : user.s

# target to generate assembly for a file
user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_System_in_C_.dir/build.make CMakeFiles/Hotel_Management_System_in_C_.dir/user.cpp.s
.PHONY : user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Hotel_Management_System_in_C_"
	@echo "... app.o"
	@echo "... app.i"
	@echo "... app.s"
	@echo "... customer.o"
	@echo "... customer.i"
	@echo "... customer.s"
	@echo "... hotel.o"
	@echo "... hotel.i"
	@echo "... hotel.s"
	@echo "... room.o"
	@echo "... room.i"
	@echo "... room.s"
	@echo "... user.o"
	@echo "... user.i"
	@echo "... user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

